spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wechart_store?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
  redis:
    host: 192.168.20.128
    port: 6379
server:
  servlet:
    context-path: /sell
  port: 8181
